name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release
      - name: Test
        run: dotnet test --configuration Release --no-build --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./TestResults/Coverage/

      - name: Report Generator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Create code coverage report
        run: reportgenerator -reports:".\**\TestResults\**\coverage.cobertura.xml" -targetdir:"coverage" -reporttypes:Html

      - name: Upload coverage reports to workflow artifact
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: coverage
          retention-days: 1

      - name: Clear Build Output
        run: dotnet clean --configuration Release
